name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Generate tag name
      id: tag
      run: echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT
      
    - name: Login to DigitalOcean Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DO_REGISTRY_TOKEN }}
        password: ${{ secrets.DO_REGISTRY_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: registry.digitalocean.com/vlandivir-main/vlandivir-2025:${{ steps.tag.outputs.TAG_NAME }}
        build-args: |
          TAG_NAME=${{ steps.tag.outputs.TAG_NAME }}
          ENVIRONMENT=PROD
          TELEGRAM_BOT_TOKEN=${{ secrets.VLANDIVIR_2025_BOT_TOKEN }}
          POSTGRES_CONNECTION_STRING=${{ secrets.POSTGRES_CONNECTION_STRING }}
          DO_SPACES_ACCESS_KEY=${{ secrets.DO_SPACES_ACCESS_KEY }}
          DO_SPACES_SECRET_KEY=${{ secrets.DO_SPACES_SECRET_KEY }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          VLANDIVIR_2025_WEBHOOK_URL=${{ secrets.VLANDIVIR_2025_WEBHOOK_URL }}
    
    - name: Clean up old Docker images
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITAL_OCEAN_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Cleaning up old vlandivir-2025 Docker images before deployment..."
          
          # Remove old vlandivir-2025 images, keeping only the 3 most recent
          docker images registry.digitalocean.com/vlandivir-main/vlandivir-2025 --format "table {{.Repository}}:{{.Tag}}\t{{.CreatedAt}}" | \
            tail -n +2 | \
            sort -k2 -r | \
            tail -n +4 | \
            awk '{print $1}' | \
            xargs -r docker rmi || true
          
          # Remove dangling images
          docker image prune -f
          
          # Remove unused images older than 24 hours
          docker image prune -a --filter "until=24h" -f
          
          # Show remaining images for verification
          echo "Remaining vlandivir-2025 images:"
          docker images registry.digitalocean.com/vlandivir-main/vlandivir-2025
          
          # Show disk space before deployment
          echo "Disk space before deployment:"
          df -h /var/lib/docker
          
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITAL_OCEAN_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull registry.digitalocean.com/vlandivir-main/vlandivir-2025:${{ steps.tag.outputs.TAG_NAME }}
          docker stop vlandivir-2025 || true
          docker rm vlandivir-2025 || true
          docker run -d -p 443:443 -e ENVIRONMENT=PROD \
            -v /root/.secret:/usr/src/app/.secret:ro \
            --name vlandivir-2025 \
            registry.digitalocean.com/vlandivir-main/vlandivir-2025:${{ steps.tag.outputs.TAG_NAME }} 
